### ISSUE TITLE
Transfer basic shiny app creation to bcgovr?

### ISSUE THREAD

**Issue by boshek** [bcgov/bcsapps#3]
:wave: @stephanieyurchak 

Cool idea! What would you think about extracting the "create a basic shiny app" into the bcgovr package? I think that could fit into that package well and could leverage the code you've written for others.

**Comment by stephanieyurchak** [comment]
@boshek 

The app template/header and footer modules would need to be generalized to be less BCStats specific, but this package really is just a small extension of the bcgovr package so I agree it would fit in well.

**Comment by boshek** [comment]
Would happy to spend time reviewing any contribution.
